src/Entity/User.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity({"email"}, message="It looks like that email is already registered")
 * @UniqueEntity({"username"}, message="Oh crazy - that username is already taken! Maybe by a Bigfoot?")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private ?string $email;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     */
    private ?string $username;

    /**
     * @var string[]
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private ?string $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BigFootSighting", mappedBy="owner")
     */
    private Collection $bigFootSightings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="owner")
     */
    private Collection $comments;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $agreedToTermsAt;

    /**
     * @ORM\Column(type="string", unique=true, nullable=true)
     */
    private ?string $confirmationToken;

    public function __construct()
    {
        $this->bigFootSightings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param string[] $roles
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|BigFootSighting[]
     */
    public function getBigFootSightings(): Collection
    {
        return $this->bigFootSightings;
    }

    public function addBigFootSighting(BigFootSighting $bigFootSighting): self
    {
        if (!$this->bigFootSightings->contains($bigFootSighting)) {
            $this->bigFootSightings[] = $bigFootSighting;
            $bigFootSighting->setOwner($this);
        }

        return $this;
    }

    public function removeBigFootSighting(BigFootSighting $bigFootSighting): self
    {
        if ($this->bigFootSightings->contains($bigFootSighting)) {
            $this->bigFootSightings->removeElement($bigFootSighting);
            // set the owning side to null (unless already changed)
            if ($bigFootSighting->getOwner() === $this) {
                $bigFootSighting->setOwner(null);
            }
        }

        return $this;
    }

    public function getAvatarUrl(): string
    {
        return sprintf('https://avatars.dicebear.com/api/bottts/%s.svg', urlencode((string) $this->getEmail()));
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function getAgreedToTermsAt(): ?DateTimeInterface
    {
        return $this->agreedToTermsAt;
    }

    public function setAgreedToTermsAt(DateTimeInterface $agreedToTermsAt): self
    {
        $this->agreedToTermsAt = $agreedToTermsAt;

        return $this;
    }

    public function getConfirmationToken(): ?string
    {
        return $this->confirmationToken;
    }

    public function setConfirmationToken(?string $confirmationToken): self
    {
        $this->confirmationToken = $confirmationToken;

        return $this;
    }
}

src/Controller/MainController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Repository\BigFootSightingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class MainController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function homepage(
        BigFootSightingRepository $bigFootSightingRepository
    ): Response {
        $sightings = $bigFootSightingRepository->findLatest(25);

        return $this->render(
            'main/homepage.html.twig',
            [
                'sightings' => $sightings,
                'mostActiveSightings' => $sightings,
            ]
        );
    }

    #[Route('/about', name: 'app_about')]
    public function about(): Response
    {
        return $this->render('main/about.html.twig');
    }
}

templates/main/_sightings.html.twig
{% for sighting in sightings %}
<tr>
    <td>
        <a class="text-white" href="{{ path('app_sighting_show', {id: sighting.id}) }}">
            {{ sighting.title }}
        </a>
    </td>
    <td class="text-nowrap">
        <time class="table-content" datetime="{{ sighting.createdAt|date('Y-m-d H:i') }}">{{ sighting.createdAt|ago }}</time>
    </td>
    <td>
        <a class="text-white table-content text-center" href="{{ path('app_sighting_show', {id: sighting.id}) }}">{{ sighting.comments|length }}</a>
    </td>
</tr>
{% endfor %}

templates/main/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aghh! I mean, hello.{% endblock %}


{% block body %}

<div class="col-3">
    <div>
        <img src="{{ asset('build/images/bigfoot.png') }}" class="big-foot-img" alt="sasquatch">
    </div>
</div>

<div class="col">
    <h1>About Us</h1>
    <p>
        We are definitely real "humans" and not sasquatch hiding in plain site. 
        We enjoy doing many popular human things, such as "showering under
        warm water" and "moving a brush on top of our teeth".
        We definitely do not enjoy hiding from other humans nor hunting
        with our bare claws, I mean, hands.
    </p>
</div>
{% endblock %}

templates/main/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="col-8">
    <h3>Recently Reported Sightings</h3>
    <small>
        <a class="btn-link" href="{{ path('app_sighting_upload') }}">Submit </a>
        yours to help us narrow down this search
    </small>

    <table class="table table-striped table-dark table-borderless table-hover">
        <thead>
            <tr class="bg-info">
                <th>Sighting Details</th>
                <th>Posted</th>
                <th>Comments</th>
            </tr>
        </thead>
        <tbody>
            {{ include('main/_sightings.html.twig') }}
        </tbody>
    </table>
</div>
<div class="col-4">
    <h3>Most Active Sightings</h3>
    <small>
        some text here
    </small>
    <table class="table table-striped table-dark table-borderless table-hover">
        <thead>
        <tr class="bg-info">
            <th>Sighting Details</th>
            <th>Posted</th>
            <th>Comments</th>
        </tr>
        </thead>
        <tbody>
        {{ include('main/_sightings.html.twig', {
            sightings: mostActiveSightings
        }) }}
        </tbody>
    </table>
</div>

{% endblock %}

templates/main/sighting_new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Upload Your Bigfoot Sighting{% endblock %}

{% block body %}
    <h2 class="col-12 mb-4">Upload your Bigfoot Sighting</h2>

    <div class="col-12">
        {{ form_start(form) }}

        {{ form_row(form.title) }}
        {{ form_row(form.description) }}
        {{ form_row(form.longitude) }}
        {{ form_row(form.latitude) }}
        {{ form_row(form.images) }}

        <div class="form-group row">
            <div class="offset-sm-2 col-sm-10">
                <button class="btn btn-primary" type="submit">Upload</button>
            </div>
        </div>

        {{ form_end(form) }}
    </div>
{% endblock %}

templates/main/sighting_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ sighting.title }} | Bigfoot{% endblock %}

{% block body %}
<div class="col">
    <div class="sighting-log-container mb-5 pb-5">
        <h2 style="font-size: 1.5rem;">{{ sighting.title }}</h2>
        <p><span class="pr-2"><i class="fa fa-clock"></i> <time datetime="{{ sighting.createdAt|date('Y-m-d H:i') }}">{{ sighting.createdAt|ago }}</time></span>
            |
            <span class="pl-2">Big Foot Believability Score: <span class="badge badge-info">{{ sighting.score }}</span> </span>
        </p>
        <div>
            {{ sighting.description }}
        </div>
    </div>

    <h3>Littlefoot (i.e. Human) Reactions</h3>

    {% for comment in sighting.comments %}
        <div class="comment-container mb-3">
            <div class="row">
                <div class="col-1">
                    <img class="px-1 py-1" src="{{ comment.owner.avatarUrl }}" alt="Avatar for {{ comment.owner.username }}">
                </div>
                <div class="col">
                    <strong>{{ comment.owner.username }}</strong>
                    <span>({{ comment.owner|user_activity_text }})</span>
                    <span class="px-2">|</span>
                    <small><i class="fa fa-clock pr-2"></i><time datetime="{{ comment.createdAt|date('Y-m-d H:i') }}">{{ comment.createdAt|ago }}</time></small>
                    <div class="pt-2">
                        {{ comment.content }}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="my-2">The little people have not commented yet...</div>
    {% endfor %}

</div>
{% endblock %}